[package]
name = "baloo_pow"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
sha2 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.5"
ring = "0.16"
itoa = "1.0"

[lib]
crate-type = ["cdylib"]